// Generated by Haxe
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Andreware : global::HaxeModuleRules {
	
	public Andreware(global::UnrealBuildTool.TargetInfo target) : base(target) {
	}
	
	
}


